// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs_ofWwnHFhkrL9pjglWa54PZXKGXhe5A',
    appId: '1:215566920705:web:f2787b8fb40c6f6686a400',
    messagingSenderId: '215566920705',
    projectId: 'sincerelysea-bk10gx',
    authDomain: 'sincerelysea-bk10gx.firebaseapp.com',
    databaseURL: 'https://sincerelysea-bk10gx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincerelysea-bk10gx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMk3eb_nKg6bo4hxaXbSkN3o6zhDhF0zA',
    appId: '1:215566920705:android:faa14449369316b686a400',
    messagingSenderId: '215566920705',
    projectId: 'sincerelysea-bk10gx',
    databaseURL: 'https://sincerelysea-bk10gx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincerelysea-bk10gx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalE3WbWDVdSbvs7OlA0E0J5WzVMgQpmg',
    appId: '1:215566920705:ios:29f0bced19c970ec86a400',
    messagingSenderId: '215566920705',
    projectId: 'sincerelysea-bk10gx',
    databaseURL: 'https://sincerelysea-bk10gx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincerelysea-bk10gx.firebasestorage.app',
    androidClientId: '215566920705-7otru2efku08so92g61ps2lcbfr2rb82.apps.googleusercontent.com',
    iosClientId: '215566920705-2m7o7q52tv4ulh0oqfnamgm6752oru8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sincerelysea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAalE3WbWDVdSbvs7OlA0E0J5WzVMgQpmg',
    appId: '1:215566920705:ios:29f0bced19c970ec86a400',
    messagingSenderId: '215566920705',
    projectId: 'sincerelysea-bk10gx',
    databaseURL: 'https://sincerelysea-bk10gx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincerelysea-bk10gx.firebasestorage.app',
    androidClientId: '215566920705-7otru2efku08so92g61ps2lcbfr2rb82.apps.googleusercontent.com',
    iosClientId: '215566920705-2m7o7q52tv4ulh0oqfnamgm6752oru8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sincerelysea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs_ofWwnHFhkrL9pjglWa54PZXKGXhe5A',
    appId: '1:215566920705:web:e2c8fea72e9da1f286a400',
    messagingSenderId: '215566920705',
    projectId: 'sincerelysea-bk10gx',
    authDomain: 'sincerelysea-bk10gx.firebaseapp.com',
    databaseURL: 'https://sincerelysea-bk10gx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sincerelysea-bk10gx.firebasestorage.app',
  );
}
